### ISSUE TITLE
Failed to open 'out/v8.pc': No such file or directory

### ISSUE THREAD

**Issue by nsivertsen** [ry/v8worker2#2]
Hi,

I'm getting the following error on macOS 10.13.4:

```
Nikolais-MBP:~ nonscio$ go get github.com/ry/v8worker2
# pkg-config --cflags out/v8.pc
Failed to open 'out/v8.pc': No such file or directory
No package 'out/v8.pc' found
pkg-config: exit status 1
```

Do you know what's going on?

Thanks!

**Comment by ry** [comment]
You need to call `./tools/build.py` in the directory in order to build libv8.

BTW you might want to make a fresh clone because I just did some force pushing. (I was playing around with having prebuilt libv8 binaries in the repo with LFS. However I don't like how that's working out - it's possible that you were hitting that.)

**Comment by nsivertsen** [comment]
Ah, I see. It's right there in the instructions! Sorry, I thought the error was abnormal.

Thank you!

And thanks for this project :)
